baseURL = "https://winningwithkonjay.com/"
languageCode = "en-us"
summaryLength = 25
[[menu.main]]
name = "About"
weight = 6
[[menu.main]]
name = "Shop"
weight = 5
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
