baseURL = "https://winningwithkonjay.com/"
languageCode = "en-us"
summaryLength = 25

[params]
cloudinary_url = "https://res.cloudinary.com/winningwithkonjay/image/upload/"

[[menu.main]]
name = "Contact"
weight = 7
[[menu.main]]
name = "About"
weight = 2
[[menu.main]]
name = "Shop"
weight = 6
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 3
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
