baseURL = "https://winningwithkonjay.com/"
languageCode = "en-us"
summaryLength = 25
[[menu.main]]
name = "Beats by Konjay"
parent = "Resources"
weight = 6
[[menu.main]]
name = "Journals"
parent = "Shop"
weight = 3
[[menu.main]]
name = "Freebies"
parent = "Resources"
weight = 3
[[menu.main]]
name = "E-books"
parent = "Resources"
weight = 2
[[menu.main]]
name = "Candles & Oils"
parent = "Shop"
weight = 2
[[menu.main]]
name = "E-courses"
parent = "Resources"
weight = 1
[[menu.main]]
name = "Apparel"
parent = "Shop"
weight = 1
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Shop"
weight = 6
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 3
[params]
cloudinary_url = "https://res.cloudinary.com/winningwithkonjay/image/upload/"
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
