baseURL = "https://winningwithkonjay.com/"
languageCode = "en-us"
summaryLength = 25
[[menu.main]]
name = "Motivational Downloads"
parent = "Resources"
weight = 3
[[menu.main]]
name = "5 Day Challenges"
parent = "Resources"
weight = 1
[[menu.main]]
name = "E-books"
parent = "Resources"
weight = 2
[[menu.main]]
name = "Beats by Konjay"
parent = "Resources"
weight = 6
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 3
[params]
cloudinary_url = "https://res.cloudinary.com/winningwithkonjay/image/upload/"
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
