baseURL = "https://winningwithkonjay.com/"
languageCode = "en-us"
summaryLength = 25
[[menu.main]]
name = "Shop"
weight = 6
[[menu.main]]
name = "Resources"
weight = 5
[[menu.main]]
name = "Contact"
url = "https://my.setmore.com/onewaysync?cKey=r191231568732083b912f5b3b450faff98552b3c2&sKey=80f1e1d4459c965140ffbba5758ae85707bb2489"
weight = 7
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 4
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
