baseURL = "https://winningwithkonjay.com/"
languageCode = "en-us"
summaryLength = 20
[[menu.main]]
name = "Winning With Konjay Podcast"
weight = 7
[[menu.main]]
name = "Resources"
weight = 6
[[menu.main]]
name = "About"
url = "/about"
weight = 2
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 5
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 3
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
