baseURL = "https://winningwithkonjay.netlify.app/"
languageCode = "en-us"
summaryLength = 20
[[menu.main]]
name = "Contact"
url = "/contact"
weight = 3
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2
[[menu.main]]
name = "Home"
url = "/"
weight = 1
